/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pe.farmacia.vista;

import com.pe.farmacia.dao.SatisfaccionDao;
import com.pe.farmacia.dao.VentaDao;
import com.pe.farmacia.daoimpl.SatisfaccionDaoImpl;
import com.pe.farmacia.daoimpl.VentaDaoImpl;
import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import static java.awt.image.ImageObserver.HEIGHT;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author 51901
 */
public class Reports extends javax.swing.JFrame {
    Date fecha = new Date();
    String fechaActual = new SimpleDateFormat("dd/MM/yyyy").format(fecha);
    
     DefaultTableModel modelo = new DefaultTableModel();
     VentaDao v = new VentaDaoImpl();
     SatisfaccionDao satisDao = new SatisfaccionDaoImpl();
    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
        setLocationRelativeTo(null);
        txtFila.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVededores = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanelVentasXanio = new javax.swing.JPanel();
        cbxAnios = new javax.swing.JComboBox<>();
        btnAnio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxmeses = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanelSatisfaccion = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableNivelSatisfacion = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableReports = new javax.swing.JTable();
        jPanelGrafico = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableVentaXVen = new javax.swing.JTable();
        btnVerVentasXnombre = new javax.swing.JButton();
        txtFila = new javax.swing.JTextField();
        jlabel10 = new javax.swing.JLabel();
        txtNombreVnededor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTotalVendedor = new javax.swing.JTextField();
        btnVentas = new javax.swing.JButton();
        btnSatisfaccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 97, 114));

        jButton1.setText("volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("GRAFICOS ");

        btnVededores.setText("VENDEDORES");
        btnVededores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVededoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVentasXanioLayout = new javax.swing.GroupLayout(jPanelVentasXanio);
        jPanelVentasXanio.setLayout(jPanelVentasXanioLayout);
        jPanelVentasXanioLayout.setHorizontalGroup(
            jPanelVentasXanioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );
        jPanelVentasXanioLayout.setVerticalGroup(
            jPanelVentasXanioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        cbxAnios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025" }));

        btnAnio.setText("ver");
        btnAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnioActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecionar año");

        jLabel4.setText("Selecionar mes");

        cbxmeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Noviembre", "Diciembre" }));

        jButton2.setText("VER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbxmeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbxAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAnio))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanelVentasXanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanelVentasXanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnio)
                            .addComponent(cbxAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxmeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab2", jPanel3);

        javax.swing.GroupLayout jPanelSatisfaccionLayout = new javax.swing.GroupLayout(jPanelSatisfaccion);
        jPanelSatisfaccion.setLayout(jPanelSatisfaccionLayout);
        jPanelSatisfaccionLayout.setHorizontalGroup(
            jPanelSatisfaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanelSatisfaccionLayout.setVerticalGroup(
            jPanelSatisfaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        TableNivelSatisfacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nivel", "Cantidad"
            }
        ));
        jScrollPane3.setViewportView(TableNivelSatisfacion);
        if (TableNivelSatisfacion.getColumnModel().getColumnCount() > 0) {
            TableNivelSatisfacion.getColumnModel().getColumn(1).setMinWidth(70);
            TableNivelSatisfacion.getColumnModel().getColumn(1).setPreferredWidth(70);
            TableNivelSatisfacion.getColumnModel().getColumn(1).setMaxWidth(70);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSatisfaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jPanelSatisfaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab3", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab4", jPanel5);

        TableReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendedor", "N° ventas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableReportsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableReports);
        if (TableReports.getColumnModel().getColumnCount() > 0) {
            TableReports.getColumnModel().getColumn(1).setMinWidth(75);
            TableReports.getColumnModel().getColumn(1).setPreferredWidth(75);
            TableReports.getColumnModel().getColumn(1).setMaxWidth(75);
        }

        javax.swing.GroupLayout jPanelGraficoLayout = new javax.swing.GroupLayout(jPanelGrafico);
        jPanelGrafico.setLayout(jPanelGraficoLayout);
        jPanelGraficoLayout.setHorizontalGroup(
            jPanelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        jPanelGraficoLayout.setVerticalGroup(
            jPanelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        TableVentaXVen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Fecha", "Total"
            }
        ));
        jScrollPane2.setViewportView(TableVentaXVen);
        if (TableVentaXVen.getColumnModel().getColumnCount() > 0) {
            TableVentaXVen.getColumnModel().getColumn(0).setMinWidth(50);
            TableVentaXVen.getColumnModel().getColumn(0).setPreferredWidth(50);
            TableVentaXVen.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btnVerVentasXnombre.setText("Ver ventas");
        btnVerVentasXnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerVentasXnombreActionPerformed(evt);
            }
        });

        jlabel10.setText("Nombre:");

        txtNombreVnededor.setEditable(false);

        jLabel2.setText("Total Ventas S/.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerVentasXnombre)
                            .addComponent(jlabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFila, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreVnededor, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(txtTotalVendedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVerVentasXnombre)
                            .addComponent(txtFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel10)
                            .addComponent(txtNombreVnededor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtTotalVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("tab1", jPanel2);

        btnVentas.setText("VENTAS");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnSatisfaccion.setText("SATISFACCION");
        btnSatisfaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatisfaccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnVededores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSatisfaccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnVededores, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSatisfaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void limpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }
    
    private void btnVededoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVededoresActionPerformed
        
        limpiarTable();
        jTabbedPane2.setSelectedIndex(3);
        MostrarCantidadeVentas();
        GraficoVetasXVendedor();
                    
          
    }//GEN-LAST:event_btnVededoresActionPerformed

    private void btnVerVentasXnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerVentasXnombreActionPerformed
        if (TableReports.getSelectedRow() > -1) {
            List<Map<String, Object>> lista = new ArrayList<>();
            modelo = (DefaultTableModel) TableVentaXVen.getModel();
            limpiarTable();
            int fila = Integer.parseInt(txtFila.getText());
            String nombre =  TableReports.getValueAt(fila, 0).toString();
            lista = v.readAll3(nombre);
            Object[] datos = new Object[4];
            for (Map<String, Object> map : lista) {
                datos[0] = map.get("id");
                datos[1] = map.get("vendedor");
                datos[2] = map.get("fecha");
                datos[3] = map.get("total");
                modelo.addRow(datos);
            }
            TableVentaXVen.setModel(modelo);
            LlenarCeldas();
        }else{
            JOptionPane.showMessageDialog(this, "Selecione un Vendedor", "Aviso", HEIGHT);
        }
    }//GEN-LAST:event_btnVerVentasXnombreActionPerformed

    private void TableReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableReportsMouseClicked
        // TODO add your handling code here
        txtNombreVnededor.setText("");
        int fila = TableReports.rowAtPoint(evt.getPoint());
        String name = TableReports.getValueAt(fila, 0).toString();
        txtFila.setText(String.valueOf(fila));
        txtNombreVnededor.setText(name);
    }//GEN-LAST:event_TableReportsMouseClicked

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        jTabbedPane2.setSelectedIndex(0);
        
        
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnSatisfaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatisfaccionActionPerformed
        jTabbedPane2.setSelectedIndex(1);
        MostrarCantidadSatisfaccion();
        GraficoVetasXSatisfaccion();
    }//GEN-LAST:event_btnSatisfaccionActionPerformed

    private void btnAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnioActionPerformed
        int index = cbxAnios.getSelectedIndex();
        String anio = (String) cbxAnios.getItemAt(index);
        System.out.println(anio);
        switch (index) {
            case 0:
                break;
            case 1:
                jPanelVentasXanio.removeAll();
                GraficosVentasxAnio(anio);
                break;
            case 2:
                jPanelVentasXanio.removeAll();
                GraficosVentasxAnio(anio);
                break;
            case 3:
                jPanelVentasXanio.removeAll();
                 GraficosVentasxAnio(anio);
                break;
    
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btnAnioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }
    public void LlenarCeldas(){
        
        txtTotalVendedor.setText("");
        double sum = 0;
        for (int i = 0; i < TableVentaXVen.getRowCount(); i++) {
                Object value = TableVentaXVen.getValueAt(i, 3);
                if (value instanceof Number) {
                    sum += ((Number) value).doubleValue();
                }
        }
        String suma = String.valueOf(sum);
        txtTotalVendedor.setText(suma);
        
    }
    
    public void MostrarCantidadeVentas(){
        
        
        Map<String, Integer> listaMpita = v.reportForCantSale();
        modelo = (DefaultTableModel) TableReports.getModel();
        Object[] ob = new Object[2];
        for (Map.Entry<String, Integer> entry : listaMpita.entrySet()) {
            ob[0] = entry.getKey(); // Clave del mapa
            ob[1] = entry.getValue(); // Valor del mapa
            modelo.addRow(ob);
        }
         
        TableReports.setModel(modelo);
        
    }
    
    public void GraficoVetasXVendedor(){
       
        Map<String, Integer> listaMpita = v.reportForCantSale();
         DefaultPieDataset data = new DefaultPieDataset();
        
         for (Map.Entry<String, Integer> entry : listaMpita.entrySet()) {
            data.setValue(entry.getKey(), entry.getValue());
            
        }
        JFreeChart grafico = ChartFactory.createPieChart(
                "ventas por vendedores",
                data,
                true,
                true,
                false
        );
        
        ChartPanel chartPanel = new ChartPanel(grafico);
        chartPanel.setPreferredSize(new Dimension(480, 295));
        
        jPanelGrafico.setLayout(new BorderLayout());
        jPanelGrafico.add(chartPanel, BorderLayout.NORTH);
        pack();
        repaint();
    }
    
    public void MostrarCantidadSatisfaccion(){
        
         Map<String, Integer> listaMpita = satisDao.cantidadDePuntuacion();
         modelo = (DefaultTableModel) TableNivelSatisfacion.getModel();
         Object[] ob = new Object[2];
         for (Map.Entry<String, Integer> entry : listaMpita.entrySet()) {
             ob[0] = entry.getKey();
             ob[1] = entry.getValue();
             modelo.addRow(ob);
         }
         
         TableNivelSatisfacion.setModel(modelo);
    }
    
    public void GraficoVetasXSatisfaccion(){
        Map<String, Integer> listaMpita = satisDao.cantidadDePuntuacion();
        DefaultPieDataset data = new DefaultPieDataset();
        for (Map.Entry<String, Integer> entry : listaMpita.entrySet()) {
            data.setValue(entry.getKey(), entry.getValue());
            
        }
        JFreeChart grafico = ChartFactory.createPieChart(
                "Nivel de Satisfacion",
                data,
                true,
                true,
                false
        );
        ChartPanel chartPanel = new ChartPanel(grafico);
        chartPanel.setPreferredSize(new Dimension(480, 295));
        jPanelSatisfaccion.setLayout(new BorderLayout());
        jPanelSatisfaccion.add(chartPanel, BorderLayout.NORTH);
        pack();
        repaint();
    }
    
    public void GraficosVentasxAnio(String anio){
        XYSeries series = new XYSeries(anio);
        int anioBuscar = Integer.parseInt(anio);
        Map<Integer, Integer> data = v.reportCantVentasXaño(anioBuscar);
        
        for (Map.Entry<Integer, Integer> entry : data.entrySet()) {
            series.add(entry.getKey(), entry.getValue());
        }
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(series);
        
        JFreeChart chart = ChartFactory.createXYLineChart("ventas por mes y año",
                "Mes",
                "Cantidad de ventas",
                dataset,
                PlotOrientation.VERTICAL,true,true,true);
        
        XYLineAndShapeRenderer render = new XYLineAndShapeRenderer();
        render.setSeriesPaint(0, Color.BLUE );
        render.setSeriesStroke(0, new BasicStroke(2));
        chart.getXYPlot().setRenderer(render);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(620, 340));
        jPanelVentasXanio.setLayout(new BorderLayout());
        jPanelVentasXanio.add(chartPanel, BorderLayout.NORTH);
        pack();
        //revalidate();
        repaint();
    }
    
    /*JFreeChart chart = ChartFactory.createXYAreaChart("ventas por mes y año",
                "Mes",
                "Cantidad de ventas",
                dataset,
                PlotOrientation.VERTICAL,true,true,false);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(620, 340));
        jPanelVentasXanio.setLayout(new BorderLayout());
        jPanelVentasXanio.add(chartPanel, BorderLayout.NORTH);
        pack();
        revalidate();
        repaint();
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableNivelSatisfacion;
    private javax.swing.JTable TableReports;
    private javax.swing.JTable TableVentaXVen;
    private javax.swing.JButton btnAnio;
    private javax.swing.JButton btnSatisfaccion;
    private javax.swing.JButton btnVededores;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btnVerVentasXnombre;
    private javax.swing.JComboBox<String> cbxAnios;
    private javax.swing.JComboBox<String> cbxmeses;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelGrafico;
    private javax.swing.JPanel jPanelSatisfaccion;
    private javax.swing.JPanel jPanelVentasXanio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel jlabel10;
    private javax.swing.JTextField txtFila;
    private javax.swing.JTextField txtNombreVnededor;
    private javax.swing.JTextField txtTotalVendedor;
    // End of variables declaration//GEN-END:variables
}
